// Generated by scripts/generate-convex-client.mjs
// Source: function_spec_1771811297926.json
// Do not edit this file manually.

export type GeneratedConvexFunctionType = 'query' | 'mutation' | 'action';
export type GeneratedConvexVisibility = 'public' | 'internal' | 'unknown';

export const convexApi = {
  ".well-known": {
    "jwks.json": {
      default: { path: "/.well-known/jwks.json", type: "action", visibility: "unknown" },
    },
    "openid-configuration": {
      default: { path: "/.well-known/openid-configuration", type: "action", visibility: "unknown" },
    },
  },
  api: {
    auth: {
      callback: {
        "*": {
          default: { path: "/api/auth/callback/*", type: "action", visibility: "unknown" },
        },
      },
      signin: {
        "*": {
          default: { path: "/api/auth/signin/*", type: "action", visibility: "unknown" },
        },
      },
    },
  },
  appState: {
    clearAll: { path: "appState:clearAll", type: "mutation", visibility: "public" },
    get: { path: "appState:get", type: "query", visibility: "public" },
    getEasyReminderState: { path: "appState:getEasyReminderState", type: "query", visibility: "public" },
    set: { path: "appState:set", type: "mutation", visibility: "public" },
    setEasyReminderState: { path: "appState:setEasyReminderState", type: "mutation", visibility: "public" },
  },
  auth: {
    isAuthenticated: { path: "auth:isAuthenticated", type: "query", visibility: "public" },
    signIn: { path: "auth:signIn", type: "action", visibility: "public" },
    signOut: { path: "auth:signOut", type: "action", visibility: "public" },
    store: { path: "auth:store", type: "mutation", visibility: "internal" },
  },
  babyProfiles: {
    create: { path: "babyProfiles:create", type: "mutation", visibility: "public" },
    getActive: { path: "babyProfiles:getActive", type: "query", visibility: "public" },
    getActiveId: { path: "babyProfiles:getActiveId", type: "query", visibility: "public" },
    getById: { path: "babyProfiles:getById", type: "query", visibility: "public" },
    list: { path: "babyProfiles:list", type: "query", visibility: "public" },
    remove: { path: "babyProfiles:remove", type: "mutation", visibility: "public" },
    setActive: { path: "babyProfiles:setActive", type: "mutation", visibility: "public" },
    update: { path: "babyProfiles:update", type: "mutation", visibility: "public" },
    updateFirstWakeTime: { path: "babyProfiles:updateFirstWakeTime", type: "mutation", visibility: "public" },
    updateSelectedEasyFormula: { path: "babyProfiles:updateSelectedEasyFormula", type: "mutation", visibility: "public" },
  },
  diaperChanges: {
    create: { path: "diaperChanges:create", type: "mutation", visibility: "public" },
    getById: { path: "diaperChanges:getById", type: "query", visibility: "public" },
    list: { path: "diaperChanges:list", type: "query", visibility: "public" },
    remove: { path: "diaperChanges:remove", type: "mutation", visibility: "public" },
    update: { path: "diaperChanges:update", type: "mutation", visibility: "public" },
  },
  diaryEntries: {
    create: { path: "diaryEntries:create", type: "mutation", visibility: "public" },
    getById: { path: "diaryEntries:getById", type: "query", visibility: "public" },
    list: { path: "diaryEntries:list", type: "query", visibility: "public" },
    remove: { path: "diaryEntries:remove", type: "mutation", visibility: "public" },
    update: { path: "diaryEntries:update", type: "mutation", visibility: "public" },
  },
  easyFormulaRules: {
    adjustPhaseTiming: { path: "easyFormulaRules:adjustPhaseTiming", type: "mutation", visibility: "public" },
    cloneAsCustom: { path: "easyFormulaRules:cloneAsCustom", type: "mutation", visibility: "public" },
    cloneForDate: { path: "easyFormulaRules:cloneForDate", type: "mutation", visibility: "public" },
    create: { path: "easyFormulaRules:create", type: "mutation", visibility: "public" },
    getByAge: { path: "easyFormulaRules:getByAge", type: "query", visibility: "public" },
    getByDate: { path: "easyFormulaRules:getByDate", type: "query", visibility: "public" },
    getById: { path: "easyFormulaRules:getById", type: "query", visibility: "public" },
    getDaySpecific: { path: "easyFormulaRules:getDaySpecific", type: "query", visibility: "public" },
    getPredefined: { path: "easyFormulaRules:getPredefined", type: "query", visibility: "public" },
    getUserCustom: { path: "easyFormulaRules:getUserCustom", type: "query", visibility: "public" },
    list: { path: "easyFormulaRules:list", type: "query", visibility: "public" },
    remove: { path: "easyFormulaRules:remove", type: "mutation", visibility: "public" },
    seedPredefined: { path: "easyFormulaRules:seedPredefined", type: "mutation", visibility: "public" },
    update: { path: "easyFormulaRules:update", type: "mutation", visibility: "public" },
  },
  feedings: {
    create: { path: "feedings:create", type: "mutation", visibility: "public" },
    getById: { path: "feedings:getById", type: "query", visibility: "public" },
    list: { path: "feedings:list", type: "query", visibility: "public" },
    remove: { path: "feedings:remove", type: "mutation", visibility: "public" },
    update: { path: "feedings:update", type: "mutation", visibility: "public" },
  },
  files: {
    deleteFile: { path: "files:deleteFile", type: "mutation", visibility: "public" },
    generateUploadUrl: { path: "files:generateUploadUrl", type: "mutation", visibility: "public" },
    getUrl: { path: "files:getUrl", type: "query", visibility: "public" },
  },
  growthRecords: {
    create: { path: "growthRecords:create", type: "mutation", visibility: "public" },
    getById: { path: "growthRecords:getById", type: "query", visibility: "public" },
    list: { path: "growthRecords:list", type: "query", visibility: "public" },
    remove: { path: "growthRecords:remove", type: "mutation", visibility: "public" },
    update: { path: "growthRecords:update", type: "mutation", visibility: "public" },
  },
  habits: {
    addBabyHabit: { path: "habits:addBabyHabit", type: "mutation", visibility: "public" },
    getBabyHabits: { path: "habits:getBabyHabits", type: "query", visibility: "public" },
    getBabyHabitsWithReminders: { path: "habits:getBabyHabitsWithReminders", type: "query", visibility: "public" },
    getDefinitionById: { path: "habits:getDefinitionById", type: "query", visibility: "public" },
    getDefinitions: { path: "habits:getDefinitions", type: "query", visibility: "public" },
    getHabitLogs: { path: "habits:getHabitLogs", type: "query", visibility: "public" },
    getHabitStreak: { path: "habits:getHabitStreak", type: "query", visibility: "public" },
    getTodayHabitLogs: { path: "habits:getTodayHabitLogs", type: "query", visibility: "public" },
    logHabit: { path: "habits:logHabit", type: "mutation", visibility: "public" },
    removeBabyHabit: { path: "habits:removeBabyHabit", type: "mutation", visibility: "public" },
    seedDefinitions: { path: "habits:seedDefinitions", type: "mutation", visibility: "public" },
    updateBabyHabitReminder: { path: "habits:updateBabyHabitReminder", type: "mutation", visibility: "public" },
  },
  healthRecords: {
    create: { path: "healthRecords:create", type: "mutation", visibility: "public" },
    getById: { path: "healthRecords:getById", type: "query", visibility: "public" },
    list: { path: "healthRecords:list", type: "query", visibility: "public" },
    remove: { path: "healthRecords:remove", type: "mutation", visibility: "public" },
    update: { path: "healthRecords:update", type: "mutation", visibility: "public" },
  },
  pumpings: {
    create: { path: "pumpings:create", type: "mutation", visibility: "public" },
    getById: { path: "pumpings:getById", type: "query", visibility: "public" },
    getInventory: { path: "pumpings:getInventory", type: "query", visibility: "public" },
    getInventoryTransactions: { path: "pumpings:getInventoryTransactions", type: "query", visibility: "public" },
    list: { path: "pumpings:list", type: "query", visibility: "public" },
    remove: { path: "pumpings:remove", type: "mutation", visibility: "public" },
    update: { path: "pumpings:update", type: "mutation", visibility: "public" },
  },
  scheduledNotifications: {
    create: { path: "scheduledNotifications:create", type: "mutation", visibility: "public" },
    getActive: { path: "scheduledNotifications:getActive", type: "query", visibility: "public" },
    getByNotificationId: { path: "scheduledNotifications:getByNotificationId", type: "query", visibility: "public" },
    list: { path: "scheduledNotifications:list", type: "query", visibility: "public" },
    removeAllForBaby: { path: "scheduledNotifications:removeAllForBaby", type: "mutation", visibility: "public" },
    removeByNotificationId: { path: "scheduledNotifications:removeByNotificationId", type: "mutation", visibility: "public" },
    removeByType: { path: "scheduledNotifications:removeByType", type: "mutation", visibility: "public" },
  },
  seed: {
    checkSeedStatus: { path: "seed:checkSeedStatus", type: "query", visibility: "public" },
    forceReseedEasyFormulas: { path: "seed:forceReseedEasyFormulas", type: "mutation", visibility: "public" },
    forceReseedVaccinationDefinitions: { path: "seed:forceReseedVaccinationDefinitions", type: "mutation", visibility: "public" },
    seedAll: { path: "seed:seedAll", type: "mutation", visibility: "public" },
    seedEasyFormulaRules: { path: "seed:seedEasyFormulaRules", type: "mutation", visibility: "public" },
    seedHabitDefinitions: { path: "seed:seedHabitDefinitions", type: "mutation", visibility: "public" },
    seedVaccinationDefinitions: { path: "seed:seedVaccinationDefinitions", type: "mutation", visibility: "public" },
    syncAllSeedData: { path: "seed:syncAllSeedData", type: "mutation", visibility: "public" },
  },
  sleepSessions: {
    create: { path: "sleepSessions:create", type: "mutation", visibility: "public" },
    getById: { path: "sleepSessions:getById", type: "query", visibility: "public" },
    list: { path: "sleepSessions:list", type: "query", visibility: "public" },
    remove: { path: "sleepSessions:remove", type: "mutation", visibility: "public" },
    update: { path: "sleepSessions:update", type: "mutation", visibility: "public" },
  },
  timeline: {
    deleteActivity: { path: "timeline:deleteActivity", type: "mutation", visibility: "public" },
    getActivities: { path: "timeline:getActivities", type: "query", visibility: "public" },
  },
  users: {
    deleteAccount: { path: "users:deleteAccount", type: "mutation", visibility: "public" },
    getCurrentUser: { path: "users:getCurrentUser", type: "query", visibility: "public" },
  },
  vaccinations: {
    checkLiveVaccineSpacing: { path: "vaccinations:checkLiveVaccineSpacing", type: "query", visibility: "public" },
    create: { path: "vaccinations:create", type: "mutation", visibility: "public" },
    getById: { path: "vaccinations:getById", type: "query", visibility: "public" },
    getCount: { path: "vaccinations:getCount", type: "query", visibility: "public" },
    getDefinitions: { path: "vaccinations:getDefinitions", type: "query", visibility: "public" },
    getDefinitionsByAgeStage: { path: "vaccinations:getDefinitionsByAgeStage", type: "query", visibility: "public" },
    getStatus: { path: "vaccinations:getStatus", type: "query", visibility: "public" },
    list: { path: "vaccinations:list", type: "query", visibility: "public" },
    remove: { path: "vaccinations:remove", type: "mutation", visibility: "public" },
    update: { path: "vaccinations:update", type: "mutation", visibility: "public" },
  },
} as const;
